"""
Fuzzer Backend Example - WebSocket Server

This is an example Python WebSocket server that:
1. Hosts the mutated RPC payloads generated by RpcMutator
2. Accepts WebSocket connections from the puppet DApp
3. Sends mutations to the connected DApps
4. Receives feedback from the wallets
5. Logs all results for analysis

Usage:
    python fuzzer_backend_example.py
    
Then expose via Ngrok:
    ngrok http 8765
"""

import asyncio
import json
import logging
import websockets
from typing import Set, Dict, Any, Optional
from datetime import datetime
import sys
from pathlib import Path

# Add agent directory to path for imports
agent_dir = Path(__file__).parent / "agent"
sys.path.insert(0, str(agent_dir))

from mutator import RpcMutator, MutationStrategy


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)


class FuzzerBackend:
    """WebSocket-based Fuzzer Backend for WALLETPROBE testing."""
    
    def __init__(self, host: str = "localhost", port: int = 8765):
        """
        Initialize the Fuzzer Backend.
        
        Args:
            host: Server host (default: localhost)
            port: Server port (default: 8765)
        """
        self.host = host
        self.port = port
        self.connected_clients: Set[websockets.WebSocketServerProtocol] = set()
        self.mutator = RpcMutator()
        self.test_results: Dict[str, Any] = {}
        self.test_counter = 0
    
    async def register_client(self, websocket: websockets.WebSocketServerProtocol):
        """Register a new connected DApp puppet."""
        self.connected_clients.add(websocket)
        logger.info(f"Client connected. Total clients: {len(self.connected_clients)}")
        
        # Send welcome message
        await websocket.send(json.dumps({
            "status": "connected",
            "message": "Connected to Fuzzer Backend",
            "timestamp": datetime.now().isoformat()
        }))
    
    async def unregister_client(self, websocket: websockets.WebSocketServerProtocol):
        """Unregister a disconnected DApp puppet."""
        self.connected_clients.discard(websocket)
        logger.info(f"Client disconnected. Total clients: {len(self.connected_clients)}")
    
    async def send_mutation_to_client(
        self,
        websocket: websockets.WebSocketServerProtocol,
        strategy: str,
        base_payload: Dict[str, Any],
        base_hints: Dict[str, Any]
    ):
        """
        Send a mutated RPC payload to a connected DApp.
        
        Args:
            websocket: Client WebSocket connection
            strategy: Mutation strategy to apply
            base_payload: Base RPC payload
            base_hints: Base hints dictionary
        """
        try:
            # Generate mutation
            mutated_payload, mutated_hints = self.mutator.mutate(
                strategy,
                base_payload,
                base_hints
            )
            
            # Create test record
            self.test_counter += 1
            test_id = f"test_{self.test_counter:05d}"
            
            # Send to client
            message = {
                "test_id": test_id,
                "strategy": strategy,
                "mutation": mutated_payload,
                "hints": mutated_hints,
                "timestamp": datetime.now().isoformat()
            }
            
            await websocket.send(json.dumps(message))
            logger.info(f"Sent mutation {test_id} ({strategy}) to client")
            
            # Store test record
            self.test_results[test_id] = {
                "strategy": strategy,
                "mutation": mutated_payload,
                "hints": mutated_hints,
                "sent_at": datetime.now().isoformat(),
                "feedback": None
            }
        
        except Exception as e:
            logger.error(f"Error sending mutation: {e}")
    
    async def broadcast_mutation(
        self,
        strategy: str,
        base_payload: Dict[str, Any],
        base_hints: Dict[str, Any]
    ):
        """
        Broadcast a mutation to all connected DApps.
        
        Args:
            strategy: Mutation strategy
            base_payload: Base RPC payload
            base_hints: Base hints dictionary
        """
        if not self.connected_clients:
            logger.warn("No connected clients to send mutation to")
            return
        
        for websocket in self.connected_clients:
            await self.send_mutation_to_client(
                websocket,
                strategy,
                base_payload,
                base_hints
            )
    
    async def handle_client(self, websocket: websockets.WebSocketServerProtocol, path: str):
        """
        Handle messages from a connected DApp puppet.
        
        Args:
            websocket: Client WebSocket connection
            path: WebSocket path
        """
        await self.register_client(websocket)
        
        try:
            async for message in websocket:
                try:
                    data = json.loads(message)
                    await self._process_client_message(data)
                except json.JSONDecodeError:
                    logger.error(f"Invalid JSON from client: {message}")
        
        except websockets.exceptions.ConnectionClosed:
            logger.info("Client connection closed")
        
        finally:
            await self.unregister_client(websocket)
    
    async def _process_client_message(self, data: Dict[str, Any]):
        """
        Process feedback from a DApp puppet.
        
        Args:
            data: Message data from client (feedback on wallet invocation)
        """
        test_id = data.get("test_id")
        status = data.get("status")
        
        if test_id in self.test_results:
            self.test_results[test_id]["feedback"] = data
            self.test_results[test_id]["received_at"] = datetime.now().isoformat()
            
            if status == "success":
                logger.info(f"✓ {test_id} - SUCCESS: {data.get('action', 'N/A')}")
            else:
                logger.error(f"✗ {test_id} - ERROR: {data.get('message', 'Unknown error')}")
        else:
            logger.warn(f"Received feedback for unknown test: {test_id}")
    
    async def start_server(self):
        """Start the WebSocket server."""
        logger.info(f"Starting Fuzzer Backend on ws://{self.host}:{self.port}")
        
        async with websockets.serve(self.handle_client, self.host, self.port):
            logger.info(f"✓ Server running on ws://{self.host}:{self.port}")
            logger.info("Waiting for DApp puppets to connect...")
            
            # Keep server running
            await asyncio.Future()
    
    async def run_interactive_fuzzing(self):
        """
        Run interactive fuzzing session in parallel with server.
        Allows sending mutations via CLI while server is running.
        """
        # Start server in background
        server_task = asyncio.create_task(self.start_server())
        
        # Wait for connections
        await asyncio.sleep(2)
        
        logger.info("\n" + "="*60)
        logger.info("INTERACTIVE FUZZING MODE")
        logger.info("="*60)
        logger.info("Commands:")
        logger.info("  1 - V4 Strip 0x")
        logger.info("  2 - V5 Unlimited Approve")
        logger.info("  3 - V7 Phishing Address")
        logger.info("  4 - V9 Mismatched ChainId")
        logger.info("  5 - V10 Corrupt Personal Sign")
        logger.info("  q - Quit")
        logger.info("="*60 + "\n")
        
        # Interactive loop (runs in thread to avoid blocking async)
        loop = asyncio.get_event_loop()
        
        while True:
            try:
                # Read input in thread
                choice = await loop.run_in_executor(None, input, "Select mutation (1-5, q to quit): ")
                
                if choice.lower() == 'q':
                    logger.info("Shutting down...")
                    break
                
                # Map choices to strategies
                strategy_map = {
                    '1': ('v4_strip_0x', self._get_v4_payload()),
                    '2': ('v5_unlimited_approve', self._get_v5_payload()),
                    '3': ('v7_phishing_address', self._get_v7_payload()),
                    '4': ('v9_mismatched_chainid', self._get_v9_payload()),
                    '5': ('v10_corrupt_personal_sign', self._get_v10_payload()),
                }
                
                if choice in strategy_map:
                    strategy, (payload, hints) = strategy_map[choice]
                    await self.broadcast_mutation(strategy, payload, hints)
                    await asyncio.sleep(1)  # Wait a bit for responses
                else:
                    logger.warn("Invalid choice")
            
            except Exception as e:
                logger.error(f"Error in interactive mode: {e}")
                break
        
        # Cancel server task
        server_task.cancel()
        try:
            await server_task
        except asyncio.CancelledError:
            pass
    
    @staticmethod
    def _get_v4_payload():
        """Return example V4 payload."""
        base_fixture = {
            "method": "eth_sendTransaction",
            "params": [{
                "from": "0x1234567890123456789012345678901234567890",
                "to": "0x0987654321098765432109876543210987654321",
                "data": "0x095ea7b3000000000000000000000000abcdefabcdefabcdefabcdefabcdefabcdefabcd0000000000000000000000000000000000000000000000008ac7230489e80000"
            }]
        }
        hints = {"parsed_intent": "ERC20 Approve", "allowance_amount_human": "10 USDT"}
        return base_fixture, hints
    
    @staticmethod
    def _get_v5_payload():
        """Return example V5 payload."""
        base_fixture = {
            "method": "eth_sendTransaction",
            "params": [{
                "from": "0x1234567890123456789012345678901234567890",
                "to": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                "data": "0x095ea7b3000000000000000000000000abcdefabcdefabcdefabcdefabcdefabcdefabcd0000000000000000000000000000000000000000000000008ac7230489e80000"
            }]
        }
        hints = {"parsed_intent": "ERC20 Approve", "allowance_amount_human": "10 USDC"}
        return base_fixture, hints
    
    @staticmethod
    def _get_v7_payload():
        """Return example V7 payload."""
        base_fixture = {
            "method": "eth_sendTransaction",
            "params": [{
                "from": "0x1234567890123456789012345678901234567890",
                "to": "0x0987654321098765432109876543210987654321",
                "value": "0x1000000000000000",
                "data": "0x"
            }]
        }
        hints = {"parsed_intent": "ETH Transfer"}
        return base_fixture, hints
    
    @staticmethod
    def _get_v9_payload():
        """Return example V9 payload."""
        base_fixture = {
            "method": "eth_signTypedData_v4",
            "params": [
                "0x1234567890123456789012345678901234567890",
                {
                    "types": {
                        "EIP712Domain": [
                            {"name": "name", "type": "string"},
                            {"name": "version", "type": "string"},
                            {"name": "chainId", "type": "uint256"},
                            {"name": "verifyingContract", "type": "address"}
                        ]
                    },
                    "domain": {
                        "name": "Uniswap",
                        "version": "1",
                        "chainId": 1,
                        "verifyingContract": "0x1111111254fb6c44bac0bed2854e76f90643097d"
                    }
                }
            ]
        }
        hints = {"parsed_intent": "EIP-712 Signature"}
        return base_fixture, hints
    
    @staticmethod
    def _get_v10_payload():
        """Return example V10 payload."""
        base_fixture = {
            "method": "personal_sign",
            "params": [
                "0x48656c6c6f2c20576f726c6421",
                "0x1234567890123456789012345678901234567890"
            ]
        }
        hints = {"parsed_intent": "personal_sign"}
        return base_fixture, hints


async def main():
    """Main entry point."""
    fuzzer = FuzzerBackend(host="0.0.0.0", port=8765)
    
    # Run with interactive mode
    try:
        await fuzzer.run_interactive_fuzzing()
    except KeyboardInterrupt:
        logger.info("\nShutdown signal received")


if __name__ == "__main__":
    # For Windows event loop compatibility
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    
    asyncio.run(main())
